sudo: required
addons:
  hosts:
    - pomodoro.dev

language: ruby

services:
  - docker

before_install:
- opt/bootstrap
- opt/docker.build

script:
- app/opt/test
- api/opt/test
- opt/docker.run DEV
- opt/docker.seed
- app/opt/test.e2e
